"""fixing user foreignkey

Revision ID: 88afad028575
Revises: 5ca481438c19
Create Date: 2024-01-06 09:00:23.565023

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '88afad028575'
down_revision: Union[str, None] = '5ca481438c19'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('urls', sa.Column('user_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'urls', 'users', ['user_id'], ['id'])
    op.drop_constraint('users_user_id_fkey', 'users', type_='foreignkey')
    op.drop_column('users', 'user_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('users_user_id_fkey', 'users', 'users', ['user_id'], ['id'])
    op.drop_constraint(None, 'urls', type_='foreignkey')
    op.drop_column('urls', 'user_id')
    # ### end Alembic commands ###
